'\" t
.\"     Title: ALTER OPERATOR CLASS
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 2010-09-16
.\"    Manual: PostgreSQL 9.0.0 Documentation
.\"    Source: PostgreSQL 9.0.0
.\"  Language: English
.\"
.TH "ALTER OPERATOR CLASS" "7" "2010-09-16" "PostgreSQL 9.0.0" "PostgreSQL 9.0.0 Documentation"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ALTER_OPERATOR_CLASS \- change the definition of an operator class
.\" ALTER OPERATOR CLASS
.SH "SYNOPSIS"
.sp
.nf
ALTER OPERATOR CLASS \fIname\fR USING \fIindex_method\fR RENAME TO \fInew_name\fR
ALTER OPERATOR CLASS \fIname\fR USING \fIindex_method\fR OWNER TO \fInew_owner\fR
.fi
.SH "DESCRIPTION"
.PP
ALTER OPERATOR CLASS
changes the definition of an operator class\&.
.PP
You must own the operator class to use
ALTER OPERATOR CLASS\&. To alter the owner, you must also be a direct or indirect member of the new owning role, and that role must have
CREATE
privilege on the operator class\(aqs schema\&. (These restrictions enforce that altering the owner doesn\(aqt do anything you couldn\(aqt do by dropping and recreating the operator class\&. However, a superuser can alter ownership of any operator class anyway\&.)
.SH "PARAMETERS"
.PP
\fIname\fR
.RS 4
The name (optionally schema\-qualified) of an existing operator class\&.
.RE
.PP
\fIindex_method\fR
.RS 4
The name of the index method this operator class is for\&.
.RE
.PP
\fInew_name\fR
.RS 4
The new name of the operator class\&.
.RE
.PP
\fInew_owner\fR
.RS 4
The new owner of the operator class\&.
.RE
.SH "COMPATIBILITY"
.PP
There is no
ALTER OPERATOR CLASS
statement in the SQL standard\&.
.SH "SEE ALSO"
CREATE OPERATOR CLASS (\fBCREATE_OPERATOR_CLASS\fR(7)), DROP OPERATOR CLASS (\fBDROP_OPERATOR_CLASS\fR(7)), ALTER OPERATOR FAMILY (\fBALTER_OPERATOR_FAMILY\fR(7))
