#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/buffer
#
# IDENTIFICATION
#    $PostgreSQL: pgsql/src/backend/snooping/auxiliary/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/snooping/auxiliary
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = bitmap.o common.o d_array.o statistics.o policy.o

include $(top_srcdir)/src/backend/common.mk
