'\" t
.\"     Title: dblink_error_message
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 2010-09-16
.\"    Manual: PostgreSQL 9.0.0 Documentation
.\"    Source: PostgreSQL 9.0.0
.\"  Language: English
.\"
.TH "DBLINK_ERROR_MESSAGE" "3" "2010-09-16" "PostgreSQL 9.0.0" "PostgreSQL 9.0.0 Documentation"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dblink_error_message \- gets last error message on the named connection
.SH "SYNOPSIS"
.sp
.nf
dblink_error_message(text connname) returns text
.fi
.SH "DESCRIPTION"
.PP
\fBdblink_error_message\fR
fetches the most recent remote error message for a given connection\&.
.SH "ARGUMENTS"
.PP
\fIconname\fR
.RS 4
Name of the connection to use\&.
.RE
.SH "RETURN VALUE"
.PP
Returns last error message, or an empty string if there has been no error in this connection\&.
.SH "EXAMPLE"
.sp
.if n \{\
.RS 4
.\}
.nf
SELECT dblink_error_message(\(aqdtest1\(aq);
.fi
.if n \{\
.RE
.\}
