'\" t
.\"     Title: SPI_getargtypeid
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 2010-09-16
.\"    Manual: PostgreSQL 9.0.0 Documentation
.\"    Source: PostgreSQL 9.0.0
.\"  Language: English
.\"
.TH "SPI_GETARGTYPEID" "3" "2010-09-16" "PostgreSQL 9.0.0" "PostgreSQL 9.0.0 Documentation"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
SPI_getargtypeid \- return the data type OID for an argument of a plan prepared by \fBSPI_prepare\fR
.\" SPI_getargtypeid
.SH "SYNOPSIS"
.sp
.nf
Oid SPI_getargtypeid(SPIPlanPtr \fIplan\fR, int \fIargIndex\fR)
.fi
.SH "DESCRIPTION"
.PP
\fBSPI_getargtypeid\fR
returns the OID representing the type id for the
\fIargIndex\fR\(aqth argument of a plan prepared by
\fBSPI_prepare\fR\&. First argument is at index zero\&.
.SH "ARGUMENTS"
.PP
SPIPlanPtr \fIplan\fR
.RS 4
execution plan (returned by
\fBSPI_prepare\fR)
.RE
.PP
int \fIargIndex\fR
.RS 4
zero based index of the argument
.RE
.SH "RETURN VALUE"
.PP
The type id of the argument at the given index\&. If the
\fIplan\fR
is
NULL
or invalid, or
\fIargIndex\fR
is less than 0 or not less than the number of arguments declared for the
\fIplan\fR,
\fISPI_result\fR
is set to
SPI_ERROR_ARGUMENT
and
InvalidOid
is returned\&.
