'\" t
.\"     Title: ALTER TRIGGER
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 2010-09-16
.\"    Manual: PostgreSQL 9.0.0 Documentation
.\"    Source: PostgreSQL 9.0.0
.\"  Language: English
.\"
.TH "ALTER TRIGGER" "7" "2010-09-16" "PostgreSQL 9.0.0" "PostgreSQL 9.0.0 Documentation"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ALTER_TRIGGER \- change the definition of a trigger
.\" ALTER TRIGGER
.SH "SYNOPSIS"
.sp
.nf
ALTER TRIGGER \fIname\fR ON \fItable\fR RENAME TO \fInew_name\fR
.fi
.SH "DESCRIPTION"
.PP
ALTER TRIGGER
changes properties of an existing trigger\&. The
RENAME
clause changes the name of the given trigger without otherwise changing the trigger definition\&.
.PP
You must own the table on which the trigger acts to be allowed to change its properties\&.
.SH "PARAMETERS"
.PP
\fIname\fR
.RS 4
The name of an existing trigger to alter\&.
.RE
.PP
\fItable\fR
.RS 4
The name of the table on which this trigger acts\&.
.RE
.PP
\fInew_name\fR
.RS 4
The new name for the trigger\&.
.RE
.SH "NOTES"
.PP
The ability to temporarily enable or disable a trigger is provided by
ALTER TABLE (\fBALTER_TABLE\fR(7)), not by
ALTER TRIGGER, because
ALTER TRIGGER
has no convenient way to express the option of enabling or disabling all of a table\(aqs triggers at once\&.
.SH "EXAMPLES"
.PP
To rename an existing trigger:
.sp
.if n \{\
.RS 4
.\}
.nf
ALTER TRIGGER emp_stamp ON emp RENAME TO emp_track_chgs;
.fi
.if n \{\
.RE
.\}
.SH "COMPATIBILITY"
.PP
ALTER TRIGGER
is a
PostgreSQL
extension of the SQL standard\&.
.SH "SEE ALSO"
ALTER TABLE (\fBALTER_TABLE\fR(7))
