'\" t
.\"     Title: ALTER VIEW
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 2010-09-16
.\"    Manual: PostgreSQL 9.0.0 Documentation
.\"    Source: PostgreSQL 9.0.0
.\"  Language: English
.\"
.TH "ALTER VIEW" "7" "2010-09-16" "PostgreSQL 9.0.0" "PostgreSQL 9.0.0 Documentation"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ALTER_VIEW \- change the definition of a view
.\" ALTER VIEW
.SH "SYNOPSIS"
.sp
.nf
ALTER VIEW \fIname\fR ALTER [ COLUMN ] \fIcolumn\fR SET DEFAULT \fIexpression\fR
ALTER VIEW \fIname\fR ALTER [ COLUMN ] \fIcolumn\fR DROP DEFAULT
ALTER VIEW \fIname\fR OWNER TO \fInew_owner\fR
ALTER VIEW \fIname\fR RENAME TO \fInew_name\fR
ALTER VIEW \fIname\fR SET SCHEMA \fInew_schema\fR
.fi
.SH "DESCRIPTION"
.PP
ALTER VIEW
changes various auxiliary properties of a view\&. (If you want to modify the view\(aqs defining query, use
CREATE OR REPLACE VIEW\&.)
.PP
You must own the view to use
ALTER VIEW\&. To change a view\(aqs schema, you must also have
CREATE
privilege on the new schema\&. To alter the owner, you must also be a direct or indirect member of the new owning role, and that role must have
CREATE
privilege on the view\(aqs schema\&. (These restrictions enforce that altering the owner doesn\(aqt do anything you couldn\(aqt do by dropping and recreating the view\&. However, a superuser can alter ownership of any view anyway\&.)
.SH "PARAMETERS"
.PP
\fIname\fR
.RS 4
The name (optionally schema\-qualified) of an existing view\&.
.RE
.PP
SET/DROP DEFAULT
.RS 4
These forms set or remove the default value for a column\&. A default value associated with a view column is inserted into
INSERT
statements on the view before the view\(aqs
ON INSERT
rule is applied, if the
INSERT
does not specify a value for the column\&.
.RE
.PP
\fInew_owner\fR
.RS 4
The user name of the new owner of the view\&.
.RE
.PP
\fInew_name\fR
.RS 4
The new name for the view\&.
.RE
.PP
\fInew_schema\fR
.RS 4
The new schema for the view\&.
.RE
.SH "NOTES"
.PP
For historical reasons,
ALTER TABLE
can be used with views too; but the only variants of
ALTER TABLE
that are allowed with views are equivalent to the ones shown above\&.
.SH "EXAMPLES"
.PP
To rename the view
foo
to
bar:
.sp
.if n \{\
.RS 4
.\}
.nf
ALTER VIEW foo RENAME TO bar;
.fi
.if n \{\
.RE
.\}
.SH "COMPATIBILITY"
.PP
ALTER VIEW
is a
PostgreSQL
extension of the SQL standard\&.
.SH "SEE ALSO"
CREATE VIEW (\fBCREATE_VIEW\fR(7)), DROP VIEW (\fBDROP_VIEW\fR(7))
