'\" t
.\"     Title: CREATE CONSTRAINT TRIGGER
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 2010-09-16
.\"    Manual: PostgreSQL 9.0.0 Documentation
.\"    Source: PostgreSQL 9.0.0
.\"  Language: English
.\"
.TH "CREATE CONSTRAINT TRIGGER" "7" "2010-09-16" "PostgreSQL 9.0.0" "PostgreSQL 9.0.0 Documentation"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
CREATE_CONSTRAINT_TRIGGER \- define a new constraint trigger
.\" CREATE CONSTRAINT TRIGGER
.SH "SYNOPSIS"
.sp
.nf
CREATE CONSTRAINT TRIGGER \fIname\fR
    AFTER \fIevent\fR [ OR \&.\&.\&. ]
    ON \fItable_name\fR
    [ FROM \fIreferenced_table_name\fR ]
    { NOT DEFERRABLE | [ DEFERRABLE ] { INITIALLY IMMEDIATE | INITIALLY DEFERRED } }
    FOR EACH ROW
    [ WHEN ( \fIcondition\fR ) ]
    EXECUTE PROCEDURE \fIfunction_name\fR ( \fIarguments\fR )
.fi
.SH "DESCRIPTION"
.PP
CREATE CONSTRAINT TRIGGER
creates a
constraint trigger\&. This is the same as a regular trigger except that the timing of the trigger firing can be adjusted using
SET CONSTRAINTS (\fBSET_CONSTRAINTS\fR(7))\&. Constraint triggers must be
AFTER ROW
triggers\&. They can be fired either at the end of the statement causing the triggering event, or at the end of the containing transaction; in the latter case they are said to be
deferred\&. A pending deferred\-trigger firing can also be forced to happen immediately by using
SET CONSTRAINTS\&.
.SH "PARAMETERS"
.PP
\fIname\fR
.RS 4
The name of the constraint trigger\&. This is also the name to use when modifying the trigger\(aqs behavior using
SET CONSTRAINTS\&. The name cannot be schema\-qualified \(em the trigger inherits the schema of its table\&.
.RE
.PP
\fIevent\fR
.RS 4
One of
INSERT,
UPDATE, or
DELETE; this specifies the event that will fire the trigger\&. Multiple events can be specified using
OR\&.
.RE
.PP
\fItable_name\fR
.RS 4
The (possibly schema\-qualified) name of the table in which the triggering events occur\&.
.RE
.PP
\fIreferenced_table_name\fR
.RS 4
The (possibly schema\-qualified) name of another table referenced by the constraint\&. This option is used for foreign\-key constraints and is not recommended for general use\&.
.RE
.PP
DEFERRABLE, NOT DEFERRABLE, INITIALLY IMMEDIATE, INITIALLY DEFERRED
.RS 4
The default timing of the trigger\&. See the
CREATE TABLE (\fBCREATE_TABLE\fR(7))
documentation for details of these constraint options\&.
.RE
.PP
\fIcondition\fR
.RS 4
A Boolean expression that determines whether the trigger function will actually be executed\&. This acts the same as in
CREATE TRIGGER (\fBCREATE_TRIGGER\fR(7))\&. Note in particular that evaluation of the
WHEN
condition is not deferred, but occurs immediately after the row update operation is performed\&. If the condition does not evaluate to
true
then the trigger is not queued for deferred execution\&.
.RE
.PP
\fIfunction_name\fR
.RS 4
The function to call when the trigger is fired\&. See
CREATE TRIGGER (\fBCREATE_TRIGGER\fR(7))
for details\&.
.RE
.PP
\fIarguments\fR
.RS 4
Optional argument strings to pass to the trigger function\&. See
CREATE TRIGGER (\fBCREATE_TRIGGER\fR(7))
for details\&.
.RE
.SH "COMPATIBILITY"
.PP
CREATE CONSTRAINT TRIGGER
is a
PostgreSQL
extension of the
SQL
standard\&.
.SH "SEE ALSO"
CREATE TRIGGER (\fBCREATE_TRIGGER\fR(7)), DROP TRIGGER (\fBDROP_TRIGGER\fR(7)), SET CONSTRAINTS (\fBSET_CONSTRAINTS\fR(7))
