'\" t
.\"     Title: dblink_is_busy
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 2010-09-16
.\"    Manual: PostgreSQL 9.0.0 Documentation
.\"    Source: PostgreSQL 9.0.0
.\"  Language: English
.\"
.TH "DBLINK_IS_BUSY" "3" "2010-09-16" "PostgreSQL 9.0.0" "PostgreSQL 9.0.0 Documentation"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dblink_is_busy \- checks if connection is busy with an async query
.SH "SYNOPSIS"
.sp
.nf
dblink_is_busy(text connname) returns int
.fi
.SH "DESCRIPTION"
.PP
\fBdblink_is_busy\fR
tests whether an async query is in progress\&.
.SH "ARGUMENTS"
.PP
\fIconname\fR
.RS 4
Name of the connection to check\&.
.RE
.SH "RETURN VALUE"
.PP
Returns 1 if connection is busy, 0 if it is not busy\&. If this function returns 0, it is guaranteed that
\fBdblink_get_result\fR
will not block\&.
.SH "EXAMPLE"
.sp
.if n \{\
.RS 4
.\}
.nf
SELECT dblink_is_busy(\(aqdtest1\(aq);
.fi
.if n \{\
.RE
.\}
