'\" t
.\"     Title: dblink_get_connections
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 2010-09-16
.\"    Manual: PostgreSQL 9.0.0 Documentation
.\"    Source: PostgreSQL 9.0.0
.\"  Language: English
.\"
.TH "DBLINK_GET_CONNECTIONS" "3" "2010-09-16" "PostgreSQL 9.0.0" "PostgreSQL 9.0.0 Documentation"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dblink_get_connections \- returns the names of all open named dblink connections
.SH "SYNOPSIS"
.sp
.nf
dblink_get_connections() returns text[]
.fi
.SH "DESCRIPTION"
.PP
\fBdblink_get_connections\fR
returns an array of the names of all open named
dblink
connections\&.
.SH "RETURN VALUE"
.PP
Returns a text array of connection names, or NULL if none\&.
.SH "EXAMPLE"
.sp
.if n \{\
.RS 4
.\}
.nf
SELECT dblink_get_connections();
.fi
.if n \{\
.RE
.\}
