#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/buffer
#
# IDENTIFICATION
#    $PostgreSQL: pgsql/src/backend/noDB/auxiliary/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/noDB/auxiliary
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = NoDBBitmap.o NoDBCol.o NoDBList.o NoDBMalloc.o NoDBMap.o NoDBRow.o NoDBArena.o NoDBSort.o NoDBRelation.o NoDBTimer.o

include $(top_srcdir)/src/backend/common.mk
